Name = input("Your Name: ")
adjective1 = input("adjective: ")
adjective2 = input("adjective: ")
noun1 = input("noun: ")
adjective3 = input("adjective: ")
noun2 = input("noun: ")
adjective4 = input("adjective: ")
adjective5 = input("adjective: ")
verb1 = input("verb: ")
verb2 = input("verb: ")
verb3 = input("verb: ")
adjective6 = input("adjective: ")
verb4 = input("verb: ")

print(f"Yesterday, {Name} and I went to the park. On our way to the {adjective1} park, we saw a {adjective2} {noun1} on a bike. We also saw big {adjective3} balloons tied to a {noun2}. Once we got to the {adjective4} park, the sky turned {adjective5}. It started to {verb1} and {verb2}. {Name} and I {verb3} all the way home. Tommorow we will try to go to the {adjective6} park again and hope it doesn't {verb4}.")