child_price = float(input("What is the price of a child's meal? "))
adult_price = float(input("What is the price of an adult's meal? "))
child_num = float(input("How many children are there? "))
adult_num = float(input("How many adults are there? "))
rate = float(input("What is the sales tax rate? "))
print()
child = float("{:.2f}" .format(child_price * child_num))
print(f"You spent ${child} on the children.")
adult = float("{:.2f}" .format(adult_price * adult_num))
print(f"You spent ${adult} on the adults. ")
sales = float(rate / 100)
subtotal = float("{:.2f}" .format(child + adult))
print(f"Subtotal: ${subtotal}")
tax = float("{:.2f}" .format(sales * subtotal))
print(f"Sales Tax: ${tax}")
total = float("{:.2f}" .format(subtotal + tax))
print(f"Total: ${total}")
print()
payment = float(input("What is the payment amount? "))
change = float("{:.2f}".format(payment - total))
print(f"Change: ${change}")